# Generated by Django 6.1.1 on 2026-09-24 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('scope', models.CharField(choices=[('tu', 'TU-wide'), ('college', 'College-wide'), ('department', 'Department')], default='college', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(blank=True, help_text='Required for college and department notices.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='colleges.college')),
                ('department', models.ForeignKey(blank=True, help_text='Required only for department notices.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='academics.department')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
