# Generated by Django 5.2.17 on 2026-09-25 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('bonafide', 'Bonafide Certificate'), ('character', 'Character Certificate'), ('recommendation', 'Recommendation Letter'), ('transcript', 'Transcript'), ('migration', 'Migration Certificate'), ('other', 'Other Document')], max_length=30)),
                ('purpose', models.TextField(help_text='Why do you need this document?')),
                ('copies', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('approved', 'Approved'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Notes from college staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to='colleges.college')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_handled', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='document_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
